### ISSUE TITLE
Its not importing null values!

### ISSUE THREAD

**Issue by harshavmb** [msathis/SQLToNoSQLImporter#6]
Hi msathis,

I used this and found that it is not importing null values present in Oracle DB. Seems attention!
Would like to help you if you want!

**Comment by msathis** [comment]
@harshavmb Hi, Can you please share the stack trace. Unfortunately, I don't have access to any oracle db at this moment.

**Comment by harshavmb** [comment]
Hi Satish,

I'm in office now.  Will send you the stack trace over this weekend.

Thanks for your prompt reply.

**Comment by msathis** [comment]
@harshavmb Hi, Any update on this? :)

**Comment by harshavmb** [comment]
Apolgies Satish for this delay. Will send your the stack trace today.

Thanks for your time.

**Comment by harshavmb** [comment]
Hi Satish,

Firstly, I would like to appreciate your patience in seeking reply from me.
Was busy this week, so completely forgot to send you a mail.

Apologies as I told I was importing from Oracle DB, actually I was
importing from MySQL and DataImporter class is not accepting null values,
so it needs some fix.

If I remove the columns with null values, it is importing data into
MongoDB.

Please find the stacktrace of the error, data used to import,
mysql-databaseconfig, mongodb-database config.

Kindly let me know if you need any other details. I'm happy to assist you
either pro-grammatically or by testing if you want.

Finally, I would like to appreciate you for this wonderful tool for
importing. It is awesome.

Peace
Harshavardhan M,
9740104262

On Mon, Nov 23, 2015 at 12:11 PM, Harshavardhan Musanalli <
harshavmb@gmail.com> wrote:

> Apolgies Satish for this delay. Will send your the stack trace today.
>
> Thanks for your time.
> On 23 Nov 2015 12:08 pm, "sathis" <notifications@github.com> wrote:
>
>> @harshavmb <https://github.com/harshavmb> Hi, Any update on this? :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/msathis/SQLToNoSQLImporter/issues/6#issuecomment-158862288>
>> .
>>
>

<dataConfig>

    <dataSource driver="com.mysql.jdbc.Driver" url="jdbc:mysql://localhost:3306/publishing" user="prod" password="Welcome1" batch-size="-1"/>
   
    <document>
       <entity name="products" pk="product_id" query="select * from dcs_product">
		  <field column="product_id" name="product_id" type="string"/>
		  <field column="display_name" name="display_name" type="string"/>
		  <field column="creation_date" name="creation_date" type="date"/>
		  <field column="workspace_id" name="workspace_id" type="string"/>
		  <field column="branch_id" name="branch_id" type="string"/>
		  <field column="checkin_date" name="checkin_date" type="date"/>
		  <field column="version" name="version" type="integer"/>
		  <field column="asset_version" name="asset_version" type="integer"/>
		  <field column="is_head" name="is_head" type="integer"/>
		  <field column="version_deleted" name="version_deleted" type="integer"/>
		  <field column="version_editable" name="version_editable" type="integer"/>
		  <field column="pred_version" name="pred_version" type="integer"/>
		  <field column="start_date" name="start_date" type="date"/>
		  <field column="end_date" name="start_date" type="date"/>
		  <field column="description" name="description" type="string"/>
		  <field column="long_description" name="long_description" type="string"/>
		  <field column="parent_cat_id" name="parent_cat_id" type="string"/>
		  <field column="product_type" name="product_type" type="integer"/>
		  <field column="admin_display" name="admin_display" type="string"/>
		  <field column="nonreturnable" name="nonreturnable" type="integer"/>
		  <field column="discountable" name="discountable" type="integer"/>          
          <field column="brand" name="brand" type="string"/>
		  <field column="disallow_recommend" name="disallow_recommend" type="integer"/>
		  <field column="manufacturer" name="manufacturer" type="string"/>
		  <field column="online_only" name="online_only" type="integer"/>   
          
	   </entity>	   
    </document>	
</dataConfig>

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SQLToNoSQLImporter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SQLToNoSQLImporter ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ SQLToNoSQLImporter ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 11 source files to E:\mongodb migration\SQLToNoSQLImporter-master\target\classes
[WARNING] /E:/mongodb migration/SQLToNoSQLImporter-master/src/main/java/net/sathis/export/sql/couch/CouchWriter.java: Some input files use or override a deprecated API.
[WARNING] /E:/mongodb migration/SQLToNoSQLImporter-master/src/main/java/net/sathis/export/sql/couch/CouchWriter.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SQLToNoSQLImporter ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory E:\mongodb migration\SQLToNoSQLImporter-master\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ SQLToNoSQLImporter ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ SQLToNoSQLImporter ---
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default) > validate @ SQLToNoSQLImporter >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default) < validate @ SQLToNoSQLImporter <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default) @ SQLToNoSQLImporter ---
15:29:09,624  INFO DataImporter:137 - Data Configuration loaded successfully
15:29:10,203 ERROR DataImporter:181 - *****  Data import failed. **********
 Reason is :
java.lang.NullPointerException
	at net.sathis.export.sql.DocBuilder.extractFieldValue(DocBuilder.java:236)
	at net.sathis.export.sql.DocBuilder.getSingleValuedEntity(DocBuilder.java:207)
	at net.sathis.export.sql.DocBuilder.getFields(DocBuilder.java:145)
	at net.sathis.export.sql.DocBuilder.execute(DocBuilder.java:127)
	at net.sathis.export.sql.DataImporter.doFullImport(DataImporter.java:177)
	at net.sathis.export.sql.DataImporter.doDataImport(DataImporter.java:96)
	at net.sathis.export.sql.SQLToNoSQLImporter.main(SQLToNoSQLImporter.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:724)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.380 s
[INFO] Finished at: 2015-11-23T15:29:10+05:30
[INFO] Final Memory: 23M/226M
[INFO] ------------------------------------------------------------------------

#mongo-db related properties 
mongo.host=127.0.0.1
mongo.useAuth=false
#mongo.user=sathis
#mongo.password=mongo
mongo.db=productcatalog
mongo.collection=products

**Comment by msathis** [comment]
@harshavmb Thanks for the StackTrace. A simple null check would fix this. I will fix it today and merge it. :)

**Comment by harshavmb** [comment]
Yup!  Actually here it should accept null values.

**Comment by msathis** [comment]
Fixed by https://github.com/msathis/SQLToNoSQLImporter/commit/ac0ef46c744eca33a16adb044044d3b671f0c4e9
