### ISSUE TITLE
Import multiple entities

### ISSUE THREAD

**Issue by puneetk91** [msathis/SQLToNoSQLImporter#8]
Hi Sathish,

I am trying to use this project for pushing data to NoSql.
But having issues for pushing multiple entities. Does it support multiple root entities, or I'll have to define the relation between all the entities like its been done in the link you've given : https://wiki.apache.org/solr/DataImportHandler#Configuration_in_data-config.xml

Does there have to be a root entity?

Thanks and regards,
Puneet

**Comment by msathis** [comment]
Sorry for late reply.. It doesnt support multiple root entries :(
